volumes:
  pg_tputinder:

services:
  tputinder_db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=tputinder_db
    volumes:
      - pg_tputinder:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5433:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - tputinder_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://tputinder_db:5432/tputinder_db'
      JAVA_OPTS: '-Xmx512m'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    kafka:
      image: confluentinc/cp-kafka:7.0.1
      networks:
        - broker-kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  broker-kafka:
    driver: bridge