spring:
  datasource:
    url: 'jdbc:postgresql://tputinder_db:5432/tputinder_db'
    username: 'user'
    password: 'pass'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    format_sql: true
    show_sql: false
  #liquibase:
    #enabled: true
    #drop-first: false
    #change-log: classpath:db/changelog/db.changelog-master.yaml