spring:
  datasource:
    url: 'jdbc:postgresql://tputinder_db:5432/tputinder_db'
    username: 'user'
    password: 'pass'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    format_sql: true
    show_sql: false
  liquibase:
    enabled: true